# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto_pb2 as proto__pb2


class LanguageServerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetChatMessage = channel.unary_unary(
                '/LanguageServerService/GetChatMessage',
                request_serializer=proto__pb2.GetChatMessageRequest.SerializeToString,
                response_deserializer=proto__pb2.GetChatMessageResponse.FromString,
                )
        self.RecordChatPanelSession = channel.unary_unary(
                '/LanguageServerService/RecordChatPanelSession',
                request_serializer=proto__pb2.RecordChatPanelSessionRequest.SerializeToString,
                response_deserializer=proto__pb2.RecordChatPanelSessionResponse.FromString,
                )


class LanguageServerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetChatMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordChatPanelSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LanguageServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetChatMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChatMessage,
                    request_deserializer=proto__pb2.GetChatMessageRequest.FromString,
                    response_serializer=proto__pb2.GetChatMessageResponse.SerializeToString,
            ),
            'RecordChatPanelSession': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordChatPanelSession,
                    request_deserializer=proto__pb2.RecordChatPanelSessionRequest.FromString,
                    response_serializer=proto__pb2.RecordChatPanelSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LanguageServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LanguageServerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetChatMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LanguageServerService/GetChatMessage',
            proto__pb2.GetChatMessageRequest.SerializeToString,
            proto__pb2.GetChatMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RecordChatPanelSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LanguageServerService/RecordChatPanelSession',
            proto__pb2.RecordChatPanelSessionRequest.SerializeToString,
            proto__pb2.RecordChatPanelSessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
